# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'\xe5\xae\xa2\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0', max_length=250, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7')),
                ('fullname', models.CharField(blank=True, db_column=b'fullname', help_text=b'\xe5\xae\xa2\xe6\x88\xb7\xe5\x85\xa8\xe7\xa7\xb0', max_length=250, null=True, verbose_name=b'\xe5\x85\xa8\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'portal_customer',
                'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('key', models.CharField(choices=[(b'keyword', b'\xe9\xa1\xb5\xe9\x9d\xa2Keyword'), (b'description', b'\xe9\xa1\xb5\xe9\x9d\xa2Description'), (b'call', b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d'), (b'mail', b'\xe8\x81\x94\xe7\xb3\xbb\xe9\x82\xae\xe7\xae\xb1')], db_column=b'key', help_text=b'*\xe9\x85\x8d\xe7\xbd\xae\xe9\xa1\xb9', max_length=16, primary_key=True, serialize=False, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe9\xa1\xb9')),
                ('value', models.CharField(blank=True, db_column=b'value', help_text=b'\xe9\x85\x8d\xe7\xbd\xae\xe5\x80\xbc', max_length=250, null=True, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe5\x80\xbc')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 810892), editable=False, help_text=b'*\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'portal_global_setting',
                'verbose_name_plural': '\u5168\u5c40\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe5\xaa\x92\xe4\xbd\x93\xe6\x96\x87\xe4\xbb\xb6\xe6\xa0\x87\xe9\xa2\x98', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('file', models.CharField(db_column=b'file', help_text=b'\xe5\xaa\x92\xe4\xbd\x93\xe6\x96\x87\xe4\xbb\xb6URL', max_length=250, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 807366), editable=False, help_text=b'*\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'portal_media',
                'verbose_name_plural': '\u5a92\u4f53\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe6\x96\xb0\xe9\x97\xbb\xe6\xa0\x87\xe9\xa2\x98', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(blank=True, db_column=b'content', help_text=b'*\xe6\x96\xb0\xe9\x97\xbb\xe5\x86\x85\xe5\xae\xb9', null=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 812176), editable=False, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('enable', models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], db_column=b'enable', default=1, help_text=b'*\xe6\x9c\x89\xe6\x95\x88\xe7\x8a\xb6\xe6\x80\x81', verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'portal_news',
                'verbose_name_plural': '\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'\xe9\x95\xbf\xe5\xba\xa6\xe9\x99\x90\xe5\x88\xb6\xe4\xb8\xba250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6', max_length=250, verbose_name=b'\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4\xe5\x90\x8d\xe7\xa7\xb0')),
                ('website', models.URLField(blank=True, db_column=b'website', help_text=b'\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4\xe7\xbd\x91\xe5\x9d\x80', null=True, verbose_name=b'\xe7\xbd\x91\xe5\x9d\x80')),
                ('logo', models.ForeignKey(blank=True, db_column=b'logo', help_text=b'120x40\xe8\xa7\x84\xe6\xa0\xbcpng\xe5\x9b\xbe\xe5\x83\x8f', max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Media', verbose_name=b'LOGO')),
            ],
            options={
                'db_table': 'portal_partner',
                'verbose_name_plural': '\u5408\u4f5c\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe4\xba\xa7\xe5\x93\x81\xe6\xa0\x87\xe9\xa2\x98,250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6\xe5\x86\x85', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('subtitle', models.CharField(blank=True, db_column=b'subtitle', help_text=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x9c\xa8\xe4\xb8\xbb\xe6\xa0\x87\xe9\xa2\x98\xe4\xb9\x8b\xe4\xb8\x8b', max_length=250, null=True, verbose_name=b'\xe5\x89\xaf\xe6\xa0\x87\xe9\xa2\x98')),
                ('enable', models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], db_column=b'enable', default=1, help_text=b'*\xe5\x90\xaf\xe7\x94\xa8\xe7\x8a\xb6\xe6\x80\x81', verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('sketch', models.TextField(blank=True, db_column=b'sketch', help_text=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x9c\xa8\xe6\xa0\x87\xe9\xa2\x98\xe4\xb9\x8b\xe4\xb8\x8b', null=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b')),
                ('keyword', models.CharField(blank=True, db_column=b'keyword', help_text=b'\xe9\xa1\xb5\xe9\x9d\xa2Keyword', max_length=250, null=True, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe5\xad\x97')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 821287), editable=False, help_text=b'*\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('partner', models.ForeignKey(blank=True, db_column=b'partner', help_text=b'\xe9\x80\x89\xe6\x8b\xa9\xe4\xba\xa7\xe5\x93\x81\xe6\x89\x80\xe5\xb1\x9e\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Partner', verbose_name=b'\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4')),
            ],
            options={
                'db_table': 'portal_product',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe5\x86\x85\xe5\xae\xb9\xe6\xa0\x87\xe9\xa2\x98,250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6\xe5\x86\x85', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(db_column=b'content', help_text=b'\xe6\x94\xaf\xe6\x8c\x81HTML\xe4\xbb\xa3\xe7\xa0\x81', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 823708), editable=False, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('position', models.IntegerField(choices=[(1, b'\xe4\xbd\x8d\xe7\xbd\xae1'), (2, b'\xe4\xbd\x8d\xe7\xbd\xae2'), (3, b'\xe4\xbd\x8d\xe7\xbd\xae3'), (0, b'\xe4\xbd\x8d\xe7\xbd\xae0'), (4, b'\xe4\xbd\x8d\xe7\xbd\xae4')], db_column=b'position', default=0, help_text=b'\xe4\xbd\x8d\xe7\xbd\xae\xe4\xbb\x8e\xe5\xb7\xa6\xe8\x87\xb3\xe5\x8f\xb3', verbose_name=b'\xe4\xbd\x8d\xe7\xbd\xae')),
                ('product', models.ForeignKey(db_column=b'product_id', help_text=b'*\xe9\x80\x89\xe6\x8b\xa9\xe6\x89\x80\xe5\xb1\x9e\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88', on_delete=django.db.models.deletion.CASCADE, to='portal.Product', verbose_name=b'\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88')),
            ],
            options={
                'db_table': 'portal_product_content',
                'verbose_name_plural': '\u4ea7\u54c1\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column=b'customer_id', help_text=b'\xe9\x80\x89\xe6\x8b\xa9\xe5\xae\xa2\xe6\x88\xb7', on_delete=django.db.models.deletion.CASCADE, to='portal.Customer', verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7')),
                ('product', models.ForeignKey(db_column=b'product_id', help_text=b'\xe9\x80\x89\xe6\x8b\xa9\xe4\xba\xa7\xe5\x93\x81', on_delete=django.db.models.deletion.CASCADE, to='portal.Product', verbose_name=b'\xe4\xba\xa7\xe5\x93\x81')),
            ],
            options={
                'db_table': 'portal_product_customer',
                'verbose_name_plural': '\u4ea7\u54c1\u5ba2\u6237\u5173\u8054',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe6\xa0\x87\xe9\xa2\x98,250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6\xe5\x86\x85', max_length=250, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('sketch', models.TextField(blank=True, db_column=b'sketch', help_text=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x9c\xa8\xe6\xa0\x87\xe9\xa2\x98\xe4\xb9\x8b\xe4\xb8\x8b', null=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b')),
                ('content', models.TextField(db_column=b'content', help_text=b'\xe6\x94\xaf\xe6\x8c\x81HTML\xe4\xbb\xa3\xe7\xa0\x81', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('keyword', models.CharField(blank=True, db_column=b'keyword', help_text=b'\xe9\xa1\xb5\xe9\x9d\xa2keyword\xe4\xbf\xa1\xe6\x81\xaf', max_length=250, null=True, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe8\xaf\x8d')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 825734), editable=False, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('enable', models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], db_column=b'enable', default=1, help_text=b'*\xe5\x90\xaf\xe7\x94\xa8\xe7\x8a\xb6\xe6\x80\x81', verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'portal_service',
                'verbose_name_plural': '\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column=b'title', help_text=b'\xe5\xb9\xbb\xe7\x81\xaf\xe7\x89\x87\xe4\xb8\xbb\xe6\xa0\x87\xe9\xa2\x98,\xe9\x95\xbf\xe5\xba\xa6\xe9\x99\x90\xe5\x88\xb6250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6', max_length=250, null=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(blank=True, db_column=b'content', help_text=b'\xe5\xb9\xbb\xe7\x81\xaf\xe7\x89\x87\xe5\x86\x85\xe5\xae\xb9,\xe5\x8f\xaf\xe4\xbd\xbf\xe7\x94\xa8HTML\xe4\xbb\xa3\xe7\xa0\x81,\xe5\x8c\xba\xe5\x9f\x9f\xe5\xa4\xa7\xe5\xb0\x8f930x250', null=True, verbose_name=b'\xe5\xb9\xbb\xe7\x81\xaf\xe7\x89\x87\xe5\x86\x85\xe5\xae\xb9')),
                ('enable', models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], db_column=b'enable', default=1, help_text=b'*\xe6\x9c\x89\xe6\x95\x88\xe7\x8a\xb6\xe6\x80\x81', verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 808966), editable=False, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'portal_slide',
                'verbose_name_plural': '\u9996\u9875\u5e7b\u706f\u7247',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88\xe6\xa0\x87\xe9\xa2\x98', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('subtitle', models.CharField(blank=True, db_column=b'subtitle', help_text=b'\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88\xe5\x89\xaf\xe6\xa0\x87\xe9\xa2\x98', max_length=250, null=True, verbose_name=b'\xe5\x89\xaf\xe6\xa0\x87\xe9\xa2\x98')),
                ('enable', models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], db_column=b'enable', default=1, help_text=b'*\xe5\x90\xaf\xe7\x94\xa8\xe7\x8a\xb6\xe6\x80\x81', verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('sketch', models.TextField(blank=True, db_column=b'sketch', help_text=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x9c\xa8\xe6\xa0\x87\xe9\xa2\x98\xe4\xb8\x8b', null=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b')),
                ('keyword', models.CharField(blank=True, db_column=b'keyword', help_text=b'\xe9\xa1\xb5\xe9\x9d\xa2keyword\xe5\xb1\x9e\xe6\x80\xa7', max_length=250, null=True, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe5\xad\x97')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 817314), editable=False, help_text=b'*\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'portal_solution',
                'verbose_name_plural': '\u89e3\u51b3\u65b9\u6848',
            },
        ),
        migrations.CreateModel(
            name='SolutionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', help_text=b'*\xe5\x86\x85\xe5\xae\xb9\xe6\xa0\x87\xe9\xa2\x98,250\xe4\xb8\xaa\xe5\xad\x97\xe7\xac\xa6\xe5\x86\x85', max_length=250, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(db_column=b'content', help_text=b'\xe6\x94\xaf\xe6\x8c\x81HTML\xe4\xbb\xa3\xe7\xa0\x81', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('update', models.DateTimeField(db_column=b'update', default=datetime.datetime(2016, 1, 5, 18, 13, 5, 819065), editable=False, help_text=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('position', models.IntegerField(choices=[(0, b'\xe4\xbd\x8d\xe7\xbd\xae0'), (1, b'\xe4\xbd\x8d\xe7\xbd\xae1'), (2, b'\xe4\xbd\x8d\xe7\xbd\xae2'), (3, b'\xe4\xbd\x8d\xe7\xbd\xae3'), (4, b'\xe4\xbd\x8d\xe7\xbd\xae4')], db_column=b'position', default=0, help_text=b'\xe4\xbd\x8d\xe7\xbd\xae\xe4\xbb\x8e\xe5\xb7\xa6\xe8\x87\xb3\xe5\x8f\xb3', verbose_name=b'\xe4\xbd\x8d\xe7\xbd\xae')),
                ('solution', models.ForeignKey(db_column=b'solution_id', help_text=b'*\xe9\x80\x89\xe6\x8b\xa9\xe6\x89\x80\xe5\xb1\x9e\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88', on_delete=django.db.models.deletion.CASCADE, to='portal.Solution', verbose_name=b'\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88')),
            ],
            options={
                'db_table': 'portal_solution_content',
                'verbose_name_plural': '\u89e3\u51b3\u65b9\u6848\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='SolutionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(db_column=b'product_id', help_text=b'*\xe9\x80\x89\xe6\x8b\xa9\xe4\xba\xa7\xe5\x93\x81', on_delete=django.db.models.deletion.CASCADE, to='portal.Product', verbose_name=b'\xe4\xba\xa7\xe5\x93\x81')),
                ('solution', models.ForeignKey(db_column=b'solution_id', help_text=b'*\xe9\x80\x89\xe6\x8b\xa9\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88', on_delete=django.db.models.deletion.CASCADE, to='portal.Solution', verbose_name=b'\xe8\xa7\xa3\xe5\x86\xb3\xe6\x96\xb9\xe6\xa1\x88')),
            ],
            options={
                'db_table': 'portal_solution_product',
                'verbose_name_plural': '\u89e3\u51b3\u65b9\u6848\u4ea7\u54c1\u5173\u8054',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ForeignKey(blank=True, db_column=b'logo', help_text=b'120x40\xe8\xa7\x84\xe6\xa0\xbcpng\xe5\x9b\xbe\xe5\x83\x8f', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Media', verbose_name=b'LOGO'),
        ),
    ]
